### ISSUE TITLE
Missing information in NCIAtlas XYZ files

### ISSUE THREAD

**Issue by RMeli** [Honza-R/NCIAtlas#1]
XYZ files in the ZIP archives downloadable from the [NCIAtlas](http://www.nciatlas.org/index.html) website do not seem to contain all the information that can be found in the files of this repository. 

For example, for `1.001_OH-O__aceticacid--acetaldehyde_080.xyz` downloaded from the website I get the following:
```
 15
charge=0 charge_a=0 charge_b=0 selection_a=1-8 selection_b=9-15 scaling=0.8
  C   -1.676709350  -0.155545695   0.000000000
  O   -0.993533620  -1.155786393   0.000000000
  O   -1.173945330   1.080177302   0.000000000
  H   -0.185940107   1.035554940   0.000000000
  C   -3.180974158  -0.156065960   0.000000000
  H   -3.550265591  -1.175547772   0.000000000
  H   -3.549007807   0.375205388  -0.876744631
  H   -3.549007807   0.375205388   0.876744631
  H    3.383761724  -1.055043540   0.874204506
  H    3.383761724  -1.055043540  -0.874204506
  H    3.718704767   0.468297407   0.000000000
  H    0.988329779  -1.029137346   0.000000000
  C    3.136216068  -0.448605116   0.000000000
  C    1.671111111  -0.165449778   0.000000000
  O    1.206475663   0.955451962   0.000000000
```
The files in this repository, however, contain additional information (benchmark energy, units, group):
https://github.com/Honza-R/NCIAtlas/blob/62dba3aafaee699d1796975515e96904f8529b27/geometries/NCIA_HB375x10/1.001_080.xyz#L1-L17

**Comment by Honza-R** [comment]
I've added a link for downloading the up-to-date version of the data set from GitHub to the NCIAtlas website. Both original and updated data are now available there.

**Comment by RMeli** [comment]
Thank you @Honza-R !
