### ISSUE TITLE
Naming convention for gometries folder in HB300SPX×10

### ISSUE THREAD

**Issue by RMeli** [Honza-R/NCIAtlas#2]
It seems that the naming convention in [HB300SPX×10](http://www.nciatlas.org/HB300SPX.html) for the geometries folder changes compared to [HB375×10 - Hydrogen bonding in organic molecules](http://www.nciatlas.org/HB375.html) and [IHB100×10 - Ionic hydrogen bonds in organic molecules](http://www.nciatlas.org/IHB100.html). In the former it is simply called `geometries` while in the latter they are called `NCIA_HB375x10_geometries` and `NCIA_IHB100x10_geometries`, respectively.

**Comment by Honza-R** [comment]
This had been solved in the new download packages built from the GitHub data. Moreover, the geometry file names had been unified too.

**Comment by RMeli** [comment]
Thank you @Honza-R !
