### ISSUE TITLE
Question on scaling

### ISSUE THREAD

**Issue by bli3936** [Honza-R/NCIAtlas#3]
Dear Developers, 

Thanks for the very organized files. I was just wondering what the scaling in xyz title line means. It's not mentioned in the readme. 

Thank you,
BL

**Comment by Honza-R** [comment]
Dear Bo Li,
The data sets featuring the dissociation curves are constructed by scaling
the intermolecular distance with respect to a reference geometry
(equilibrium in all but the R739x5 set). This is described in more detail
in the papers, especially in the first one on H-bonds. These papers can
also be found at chemrxiv.

Best regards,
Jan

**Comment by bli3936** [comment]
Dear Dr. Rezac,

Many thanks for the response!  I've read into the paper but I just wanted to double check with you: 

1. Are the scans all rigid, i.e., the scaling that you mentioned in the paper is only about the global translation of some fragment? 
2. Are the benchmark_Eint data defined on each geometry (i.e. computed without any geometric relaxation)? 

These are quite important aspects for correctly using the data, so I just wanted to make sure. 

Thanks,
Bo

**Comment by Honza-R** [comment]
1) Yes, it is only translation of one of the fragments
2) The interaction is computed without relaxation, the fragments are in the
same geometry as in the dimer

**Comment by bli3936** [comment]
Thank you!
