### ISSUE TITLE
Monomer geometries

### ISSUE THREAD

**Issue by KirillKulaev** [Honza-R/NCIAtlas#4]
Do I understand correctly that in the D1200 dataset, the energy values from data_defenintion file was calculated using monomer geometry from the same geometry/xyz files in which the complex is written? Just like E(complex) - E(compound a) - E(compound b) from the same file?

**Comment by Honza-R** [comment]
In all the data sets, the interaction energy is computed using frozen
geometry of the monomers taken from the dimer.
